[19/Jun/2017 23:29:22] INFO [restaurantes.views:10] Una visita más
[19/Jun/2017 23:29:22] ERROR [django.request:135] Internal Server Error: /restaurantes/
Traceback (most recent call last):
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/entrega1/restaurantes/views.py", line 12, in index
    return render(request,'index.html',context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/defaulttags.py", line 983, in do_if
    nodelist = parser.parse(('endif',))
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/defaulttags.py", line 1376, in url
    viewname = parser.compile_filter(bits[1])
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''registro' from ''registro'
[19/Jun/2017 23:29:22] ERROR [django.server:124] "GET /restaurantes/ HTTP/1.1" 500 179761
[19/Jun/2017 23:30:24] INFO [restaurantes.views:10] Una visita más
[19/Jun/2017 23:30:24] ERROR [django.request:135] Internal Server Error: /restaurantes/
Traceback (most recent call last):
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/entrega1/restaurantes/views.py", line 12, in index
    return render(request,'index.html',context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registro' not found. 'registro' is not a valid view function or pattern name.
[19/Jun/2017 23:30:24] ERROR [django.server:124] "GET /restaurantes/ HTTP/1.1" 500 167810
[19/Jun/2017 23:32:28] INFO [restaurantes.views:10] Una visita más
[19/Jun/2017 23:33:22] INFO [restaurantes.views:10] Una visita más
[19/Jun/2017 23:33:29] INFO [restaurantes.views:10] Una visita más
[19/Jun/2017 23:33:54] INFO [restaurantes.views:10] Una visita más
[20/Jun/2017 00:03:05] ERROR [django.request:135] Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/defaulttags.py", line 1038, in find_library
    return parser.libraries[name]
KeyError: 'bootstrap4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader.py", line 48, in select_template
    return engine.get_template(template_name)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/defaulttags.py", line 1095, in load
    lib = find_library(parser, name)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/template/defaulttags.py", line 1042, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'bootstrap4' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
static
staticfiles
tz
[20/Jun/2017 00:03:05] ERROR [django.server:124] "GET /accounts/register/ HTTP/1.1" 500 151990
[20/Jun/2017 00:05:50] INFO [restaurantes.views:10] Una visita más
[20/Jun/2017 00:06:50] ERROR [django.request:135] Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/registration/views.py", line 41, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/home/pablo/Facultad/SSBW/SSBW/Entrega1/lib/python3.5/site-packages/registration/views.py", line 45, in form_valid
    success_url = self.get_success_url(new_user)
TypeError: get_success_url() missing 1 required positional argument: 'user'
[20/Jun/2017 00:06:50] ERROR [django.server:124] "POST /accounts/register/ HTTP/1.1" 500 105552
[20/Jun/2017 00:07:35] INFO [restaurantes.views:10] Una visita más
